
[Gameplay]
	#The duration of how long Wind Blows fired by Wind Blowers last in ticks
	"Wind Blow Duration" = 50

[Worldgen]
	#The weighting of Ancient Aether Regions in the Aether
	"Ancient Aether Region Weight" = 20

[Experimental]
	#Enables features of the mod that are work in progress
	"Experimental Features" = false

