#Description for customizing the skyarena.json config can be found at the following link:
#https://github.com/JrDemiurg/DemisSkyArenaMod/wiki
#
#
#If true, the reward key can only be used on empty chests.
#If false, the chest's contents will be cleared before being filled with loot.
requireEmptyChest = false
#
#If true, a defeat message will be shown when the player leaves the arena.
enableLossMessageLeave = true
#
#If true, a defeat message will be shown when the player dies in battle.
enableLossMessageDeath = true
#
#If true, when mobs receive the Glowing effect, a message will appear recommending leaving the arena to restart the battle.
#The message appears only once per game session.
enableUnclaimedRewardMessage = true

